// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6aaDYE4U_h72URmJLWFWXdd2yF_w834E',
    appId: '1:855596293493:web:b1ff88fb1ac222d401873c',
    messagingSenderId: '855596293493',
    projectId: 'chating-1a019',
    authDomain: 'chating-1a019.firebaseapp.com',
    storageBucket: 'chating-1a019.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjRX90c9eanNIxElqS8i305UVmewi5tGM',
    appId: '1:855596293493:android:9450ef015d1eaa3401873c',
    messagingSenderId: '855596293493',
    projectId: 'chating-1a019',
    storageBucket: 'chating-1a019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqEy1dRNxuWaYH27IIqj1iTrRUR4biLc',
    appId: '1:855596293493:ios:7c8a1896042be79c01873c',
    messagingSenderId: '855596293493',
    projectId: 'chating-1a019',
    storageBucket: 'chating-1a019.appspot.com',
    iosBundleId: 'com.example.chatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqEy1dRNxuWaYH27IIqj1iTrRUR4biLc',
    appId: '1:855596293493:ios:9eafaddd7afd2f5901873c',
    messagingSenderId: '855596293493',
    projectId: 'chating-1a019',
    storageBucket: 'chating-1a019.appspot.com',
    iosBundleId: 'com.example.chatting.RunnerTests',
  );
}
